// Textes légaux (fr, en). Les autres langues affichent la version anglaise.
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

export function legalHTML(which, lang, LEGAL, SITE) {
  const LANG = lang === "fr" ? "fr" : "en";
  const dispLang = lang;
  function L(k){if(LEGAL[k])return esc(LEGAL[k]);const fr=LANG==="fr";
  const n={editeur:fr?"nom ou raison sociale de l'éditeur":"publisher name",forme:fr?"forme juridique et capital":"legal form and share capital",adresse:fr?"adresse du siège":"registered address",siren:fr?"SIREN / RCS":"company registration number",email:fr?"e-mail de contact":"contact e-mail",directeur:fr?"directeur de publication":"publication director"}[k];
  return`<span class="todo">[${fr?"à compléter":"to be completed"} : ${n}]</span>`}

  const legalDate = () => { try { return new Intl.DateTimeFormat(dispLang, { dateStyle: "long" }).format(new Date(LEGAL.majLe)); } catch { return LEGAL.majLe; } };
  const LEGAL_TXT={
fr:{
mentions:()=>`<h2>Mentions légales</h2><p class="upd">Dernière mise à jour : ${legalDate()}</p>
<p>Conformément à l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique (LCEN).</p>
<h3>Éditeur</h3><p>Contexthèque est édité par <strong>${L("editeur")}</strong><br>${L("forme")}<br>Siège : ${L("adresse")}<br>Immatriculation : ${L("siren")}<br>Contact : ${L("email")}</p>
<h3>Directeur de la publication</h3><p>${L("directeur")}</p>
<h3>Hébergement</h3><p>${esc(LEGAL.hebergeur)}</p>
<h3>Contenus publiés par les membres</h3><p>Les ressources (contextes, prompts, datasets, configurations) sont publiées par les membres sous leur seule responsabilité. L'éditeur agit en qualité d'hébergeur de ces contenus au sens de l'article 6-I-2 de la LCEN et du règlement (UE) 2022/2065 sur les services numériques : il n'exerce pas de contrôle préalable mais retire promptement tout contenu manifestement illicite qui lui est signalé.</p>
<h3>Propriété intellectuelle</h3><p>La marque Contexthèque, ainsi que la structure, le code et la charte graphique du service, sont la propriété de l'éditeur. Les ressources restent la propriété de leurs auteurs et sont réutilisables selon la licence choisie par chacun.</p>
<h3>Signalement</h3><p>Pour signaler un contenu illicite, écrivez à ${L("email")} en précisant l'identifiant de la ressource, le motif et, le cas échéant, les droits en cause. Voir aussi les <a href="#/legal/cgu">conditions générales d'utilisation</a>.</p>`,
cgu:()=>`<h2>Conditions générales d'utilisation</h2><p class="upd">Dernière mise à jour : ${legalDate()}</p>
<h3>1. Objet</h3><p>Les présentes conditions régissent l'utilisation de Contexthèque, service qui permet de publier, rechercher, tester et réutiliser des ressources pour modèles de langage : contextes d'in-context learning, prompts, datasets et configurations de fine-tuning. Utiliser le service vaut acceptation de ces conditions.</p>
<h3>2. Accès</h3><p>La consultation est libre et gratuite. La publication, les mentions « j'aime » et le bac à sable nécessitent un compte ; le membre est responsable de la confidentialité de ses identifiants. L'éditeur peut suspendre ou faire évoluer le service à tout moment, notamment pour maintenance.</p>
<h3>3. Publication de contenus</h3><p>En publiant une ressource, le membre garantit :</p><ul><li>être l'auteur du contenu ou disposer des droits nécessaires pour le diffuser sous la licence choisie ;</li><li>que le contenu ne contient pas de données personnelles de tiers, sauf anonymisation effective ou base légale au sens du RGPD ;</li><li>que le contenu ne reproduit pas d'œuvres protégées (textes, code, jeux de données) en violation des droits de leurs titulaires ni des conditions d'utilisation d'un fournisseur de modèle.</li></ul><p>Le membre reste seul responsable de ses contenus et garantit l'éditeur contre toute réclamation de tiers à leur sujet.</p>
<h3>4. Licences</h3><p>Chaque ressource est diffusée sous la licence choisie par son auteur. À défaut de licence précisée, tous les droits sont réservés : les autres membres peuvent consulter et tester la ressource dans le service, mais doivent obtenir l'accord de l'auteur pour toute autre réutilisation. Le membre concède à l'éditeur le droit non exclusif et gratuit d'héberger, afficher et reproduire le contenu dans la seule mesure nécessaire au fonctionnement du service.</p>
<h3>5. Contenus interdits</h3><p>Sont notamment interdits : les contenus illicites, haineux, diffamatoires ou portant atteinte à la vie privée ; les datasets ou prompts conçus pour générer des contenus illicites, contourner les protections d'un modèle ou nuire à des personnes ; les logiciels malveillants ; les données personnelles sensibles au sens de l'article 9 du RGPD.</p>
<h3 id="signalement">6. Signalement et retrait</h3><p>Tout contenu peut être signalé à ${L("email")}. L'éditeur examine les signalements et peut retirer une ressource ou restreindre l'accès d'un membre en cas de manquement, après information de l'intéressé sauf urgence ou obligation légale.</p>
<h3>7. Fonction de test par IA</h3><p>L'onglet « Tester » envoie la ressource et votre saisie au modèle de langage configuré par l'éditeur (fournisseur tiers ou modèle auto-hébergé). Les réponses générées peuvent être inexactes ; elles sont fournies à titre indicatif et ne doivent pas être utilisées sans vérification. Ne saisissez pas de données personnelles ou confidentielles dans le bac à sable.</p>
<h3>8. Multilinguisme</h3><p>L'interface est proposée en plusieurs langues. Les contenus publiés ne sont pas traduits et restent dans la langue choisie par leur auteur. En cas de divergence entre les versions linguistiques des présentes conditions, la version française prévaut.</p>
<h3>9. Responsabilité</h3><p>Le service est fourni en l'état. L'éditeur ne garantit ni l'exactitude, ni la qualité, ni l'adéquation des ressources publiées par les membres, ni les résultats d'un entraînement ou d'un modèle obtenu à partir de celles-ci. Sa responsabilité ne peut être engagée qu'en cas de faute prouvée et dans les limites prévues par la loi.</p>
<h3 id="donnees">10. Données personnelles</h3><p>Responsable du traitement : ${L("editeur")}, joignable à ${L("email")}.</p><ul>
<li><strong>Données traitées :</strong> identifiant de compte, adresse e-mail (jamais affichée publiquement), mot de passe (stocké sous forme chiffrée), pseudo d'auteur, contenus publiés, mentions « j'aime » et compteurs d'utilisation. Les saisies du bac à sable sont transmises au fournisseur du modèle et ne sont pas conservées par le service. La langue d'interface est conservée uniquement dans votre navigateur.</li>
<li><strong>Finalités et base légale :</strong> fournir le service, attribuer les publications et envoyer les e-mails liés au compte (bienvenue, alerte à chaque connexion, mot de passe oublié), sur le fondement de l'exécution des présentes conditions (art. 6-1-b RGPD).</li>
<li><strong>Durée :</strong> jusqu'à la suppression du compte ou de la ressource, sur demande ou à la fermeture du service.</li>
<li><strong>Destinataires :</strong> les visiteurs du hub pour les contenus publiés ; l'hébergeur et, pour les saisies du bac à sable, le fournisseur du modèle, en qualité de sous-traitants, ainsi que Proton AG (Suisse) pour l'envoi des e-mails. Si ce fournisseur est situé hors de l'Union européenne, les transferts sont encadrés par les garanties qu'il propose.</li>
<li><strong>Vos droits :</strong> accès, rectification, effacement, limitation, opposition et portabilité, en écrivant à ${L("email")}. Vous pouvez introduire une réclamation auprès de la CNIL (cnil.fr).</li></ul>
<p>Le service n'utilise que des cookies techniques nécessaires (session et protection CSRF), sans cookie publicitaire ni traceur de mesure d'audience.</p>
<h3>11. Modification des conditions</h3><p>L'éditeur peut modifier les présentes conditions. La version en vigueur est celle affichée sur cette page ; les modifications substantielles sont signalées aux membres.</p>
<h3>12. Droit applicable</h3><p>Les présentes conditions sont soumises au droit français. À défaut de résolution amiable, tout litige relève des tribunaux compétents selon les règles de droit commun.</p>`},
en:{
mentions:()=>`<h2>Legal notice</h2><p class="upd">Last updated: ${legalDate()}</p>
<p>Pursuant to Article 6 of French Law No. 2004-575 of 21 June 2004 on confidence in the digital economy (LCEN).</p>
<h3>Publisher</h3><p>Contexthèque is published by <strong>${L("editeur")}</strong><br>${L("forme")}<br>Registered office: ${L("adresse")}<br>Registration: ${L("siren")}<br>Contact: ${L("email")}</p>
<h3>Publication director</h3><p>${L("directeur")}</p>
<h3>Hosting</h3><p>${esc(LEGAL.hebergeur)}</p>
<h3>Content published by members</h3><p>Resources (contexts, prompts, datasets, configurations) are published by members under their sole responsibility. The publisher acts as a hosting provider for this content within the meaning of Article 6-I-2 of the LCEN and Regulation (EU) 2022/2065 (Digital Services Act): it does not review content beforehand but promptly removes any manifestly illegal content reported to it.</p>
<h3>Intellectual property</h3><p>The Contexthèque brand, and the structure, code and visual identity of the service, are the property of the publisher. Resources remain the property of their authors and may be reused under the license each author chooses.</p>
<h3>Reporting</h3><p>To report illegal content, write to ${L("email")} stating the resource ID, the reason and, where applicable, the rights concerned. See also the <a href="#/legal/cgu">terms of use</a>.</p>`,
cgu:()=>`<h2>Terms of use</h2><p class="upd">Last updated: ${legalDate()}</p>
<h3>1. Purpose</h3><p>These terms govern the use of Contexthèque, a service for publishing, searching, testing and reusing resources for language models: in-context learning contexts, prompts, datasets and fine-tuning configurations. Using the service means accepting these terms.</p>
<h3>2. Access</h3><p>Browsing is open and free. Publishing, liking and the sandbox require an account; members are responsible for keeping their credentials confidential. The publisher may suspend or change the service at any time, including for maintenance.</p>
<h3>3. Publishing content</h3><p>By publishing a resource, the member warrants that:</p><ul><li>they are the author of the content or hold the rights needed to distribute it under the chosen license;</li><li>the content contains no third-party personal data, unless effectively anonymized or processed on a legal basis under the GDPR;</li><li>the content does not reproduce protected works (text, code, datasets) in breach of their owners' rights or of a model provider's terms of use.</li></ul><p>The member remains solely responsible for their content and indemnifies the publisher against any third-party claim relating to it.</p>
<h3>4. Licenses</h3><p>Each resource is distributed under the license chosen by its author. Where no license is specified, all rights are reserved: other members may view and test the resource within the service, but need the author's permission for any other reuse. The member grants the publisher a non-exclusive, royalty-free right to host, display and reproduce the content solely as needed to operate the service.</p>
<h3>5. Prohibited content</h3><p>Prohibited content includes: illegal, hateful or defamatory content, or content that infringes privacy; datasets or prompts designed to generate illegal content, bypass a model's safeguards or harm people; malware; sensitive personal data within the meaning of Article 9 GDPR.</p>
<h3 id="signalement">6. Reporting and removal</h3><p>Any content may be reported to ${L("email")}. The publisher reviews reports and may remove a resource or restrict a member's access in case of breach, after informing them unless urgent or required by law.</p>
<h3>7. AI testing feature</h3><p>The "Try it" tab sends the resource and your input to the language model configured by the publisher (third-party provider or self-hosted model). Generated answers may be inaccurate; they are indicative only and must be checked before use. Do not enter personal or confidential data in the sandbox.</p>
<h3>8. Languages</h3><p>The interface is available in several languages. Published content is not translated and stays in the language chosen by its author. In case of discrepancy between language versions of these terms, the French version prevails.</p>
<h3>9. Liability</h3><p>The service is provided as is. The publisher does not guarantee the accuracy, quality or fitness of resources published by members, nor the results of any training or model derived from them. Its liability may only be engaged for proven fault and within the limits set by law.</p>
<h3 id="donnees">10. Personal data</h3><p>Data controller: ${L("editeur")}, reachable at ${L("email")}.</p><ul>
<li><strong>Data processed:</strong> account username, e-mail address (never shown publicly), password (stored hashed), author handle, published content, likes and usage counters. Sandbox inputs are sent to the model provider and are not kept by the service. The interface language is stored only in your browser.</li>
<li><strong>Purposes and legal basis:</strong> providing the service, attributing publications and sending account e-mails (welcome, alert on each sign-in, password reset), on the basis of performing these terms (Art. 6(1)(b) GDPR).</li>
<li><strong>Retention:</strong> until the account or resource is deleted, on request or when the service closes.</li>
<li><strong>Recipients:</strong> hub visitors for published content; the host and, for sandbox inputs, the model provider, as processors, as well as Proton AG (Switzerland) for sending e-mails. Where that provider is located outside the European Union, transfers are covered by the safeguards it offers.</li>
<li><strong>Your rights:</strong> access, rectification, erasure, restriction, objection and portability, by writing to ${L("email")}. You may lodge a complaint with the CNIL (cnil.fr) or your local supervisory authority.</li></ul>
<p>The service only uses strictly necessary technical cookies (session and CSRF protection), with no advertising cookies or audience-measurement trackers.</p>
<h3>11. Changes</h3><p>The publisher may amend these terms. The version in force is the one shown on this page; material changes are notified to members.</p>
<h3>12. Governing law</h3><p>These terms are governed by French law. Failing an amicable settlement, any dispute falls under the jurisdiction of the competent courts under ordinary rules.</p>`}
};

  return LEGAL_TXT[LANG][which]().split("Contexthèque").join(esc(SITE));
}
